// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbs6NaDO4XXAZDig9ezoxCSn3EHyDRX44',
    appId: '1:909990358350:web:c061111aa757784094421f',
    messagingSenderId: '909990358350',
    projectId: 'book-app-final-510a6',
    authDomain: 'book-app-final-510a6.firebaseapp.com',
    storageBucket: 'book-app-final-510a6.firebasestorage.app',
    measurementId: 'G-4L95YFZPPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGP5YMlfLeqHRzOdalAYJj2Ab1ii0c_QM',
    appId: '1:909990358350:android:fc13a0ff54db762094421f',
    messagingSenderId: '909990358350',
    projectId: 'book-app-final-510a6',
    storageBucket: 'book-app-final-510a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCneDEl3cXvGHonTls_zqPShUK5st20rn8',
    appId: '1:909990358350:ios:56bb489607fd1d0f94421f',
    messagingSenderId: '909990358350',
    projectId: 'book-app-final-510a6',
    storageBucket: 'book-app-final-510a6.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );
}
